# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-04-02 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raidadaptor',
            name='memo',
        ),
        migrations.AddField(
            model_name='raidadaptor',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='remarks'),
        ),
        migrations.AlterField(
            model_name='raidadaptor',
            name='model',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='RaidModel'),
        ),
        migrations.AlterField(
            model_name='raidadaptor',
            name='slot',
            field=models.CharField(max_length=64, verbose_name='RaidSlot'),
        ),
        migrations.AlterField(
            model_name='raidadaptor',
            name='sn',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='SNNum'),
        ),
    ]
